services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - db_data:/var/www/html/uploads
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

