version: '3.9'

services:
  web:
    build: .
    container_name: war_game_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - war_game_net

  uploader:
    image: php:8.2-cli
    container_name: war_game_uploader
    depends_on:
      - web
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - war_game_net
    command: tail -f /dev/null 

networks:
  war_game_net:
    driver: bridge